# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package
permissions:
  contents: read

on:
  schedule:
    - cron: "0 22 * * *"

jobs:
  test:
    environment: e2e
    env:
      PYTHONPATH: $PYTHONPATH:src
      VABALI_USERNAME: ${{ secrets.VABALI_USERNAME }}
      VABALI_PASSWORD: ${{ secrets.VABALI_PASSWORD }}
      VABALI_E2E_APPOINTMENT_ID: ${{ secrets.VABALI_E2E_APPOINTMENT_ID }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        uv sync --all-extras --dev
    - name: Run tests
      run: uv run pytest tests/e2e
